change alert to matdialog in demo page
ghostfolio/ghostfolio pull request #1358
Opened 2022-10-15 16:58 UTC by RizkyRajitha

changed browser alert to matdialog in demo page

https://github.com/ghostfolio/ghostfolio/issues/1314

@dtslvr can you share you thoughts on this.

Thank you

2022-10-15 19:16 UTC, dtslvr requested changes

2022-10-15 19:16 UTC, dtslvr commented on apps/client/src/app/pages/demo/demo-page-dialog.html
> +<h3 mat-dialog-title>{{text}}</h3>
Can you move this template to `libs/ui/src/lib/alert/alert.component.html`

2022-10-15 19:16 UTC, dtslvr commented on apps/client/src/app/pages/demo/demo-page.component.ts
> +@Component({
Can you move this component to `libs/ui/src/lib/alert/alert.component.ts`?

2022-10-15 19:16 UTC, dtslvr commented on apps/client/src/app/pages/demo/demo-page-dialog.html
> +<h3 mat-dialog-title>{{text}}</h3>
Can you add an _Okay_ button?

```
<div mat-dialog-actions>
  <button cdkFocusInitial i18n mat-button mat-dialog-close>Okay</button>
</div>
```

2022-10-15 19:17 UTC, dtslvr commented
> @dtslvr can you share you thoughts on this.

Thanks for the update @RizkyRajitha 👍🏻  It is going in the right direction. I have added some comments.

2022-10-16 17:39 UTC, RizkyRajitha commented
thank you @dtslvr for your feedback will update

2022-11-19 11:06 UTC, dtslvr commented
Hey @RizkyRajitha

Are you planning to resume this pull request?

2022-11-22 17:12 UTC, RizkyRajitha commented
hi @dtslvr ,
sorry for delayed reply , 
i am planning to work on these changes .

2023-09-23 07:50 UTC, dtslvr commented
There has been no activity on this PR for an extended period. Closing it now.

2023-09-23 07:50 UTC, closed without merging