Feature/convert into pwa
ghostfolio/ghostfolio pull request #1436
Opened 2022-11-09 19:56 UTC by albertsalles4

Convert into a Progressive Web App. I set up `@angular/pwa` following [this comment](https://github.com/nrwl/nx/discussions/7183#discussioncomment-1409454):
> ```shell
> npm install @angular/pwa --save-dev
> nx g @angular/pwa:ng-add --project *project-name*
> ```

I only had to change a couple of things in `site.webmanifest`:
- The icons src url was prepended with `/en` and I removed it because they could not be found.
- The first icon was tagged as maskable so that it can be displayed safely.
- The `start_url` should be a relative path. In this case we use `/en/` as root because it is _the preferred URL that should be loaded when the user launches the web application_, as explained [here](https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url).

Also, I have added the theme-color meta tag in `index.html`. I copied the value from `site.webmanifest`.

I have tested that the PWA works using Lighthouse:
![image](https://user-images.githubusercontent.com/31882348/200926265-f7cae16a-2497-4d50-b7d3-1e312ec4957c.png)

It should be noted that Lighthouse report indicates that it is not _PWA optimized_ because the value of `"background_color": "transparent"` in `site.webmanifest` is not accepted, we should set it to CSS color or HEX value. I can add it if you tell me which color is fine :)

Additionally, I also tested it on a selfhosted server and it works fine.

2022-11-10 18:30 UTC, dtslvr requested changes
Thanks @albertsalles4! Looking forward to try it

2022-11-10 18:30 UTC, dtslvr commented on apps/client/src/assets/site.webmanifest
>    "theme_color": "#FFFFFF",
`background_color: "#FFFFFF"` should also be fine (see above)

2022-11-10 18:30 UTC, dtslvr commented on apps/client/project.json
> +            "glob": "site.webmanifest",
Can you move this below the `sitemap.xml` block?

2022-11-10 18:30 UTC, dtslvr commented on package.json
> +    "@angular/pwa": "^14.2.9",
Can you fix the version to `14.2.9` please and run `yarn install` again: `"@angular/pwa": "14.2.9"`

2022-11-10 19:23 UTC, albertsalles4 commented
Thanks for your response @dtslvr! Changes applied 😄. May I suggest adding PWA to the features list in the `README.md` file.

2022-11-11 15:49 UTC, dtslvr approved these changes
> Thanks for your response @dtslvr! Changes applied 😄. May I suggest adding PWA to the features list in the `README.md` file.

Thank you for your changes @albertsalles4! I still have reservations because of my bad experience 🙈 I just hope there is no problem with the auto update. But if it works, it can definitely be added to the features: `✅ Progressive Web App (PWA) with a mobile-first design`

2022-11-11 15:50 UTC, merged