Feature/translation pt
ghostfolio/ghostfolio pull request #2073
Opened 2023-06-13 22:39 UTC by luispinho

**WIP** (still more translations, other PRs will be opened in the future).
 
Complete Portuguese translations for Home Screen.
Add other various Portuguese translations.

2023-06-14 18:04 UTC, dtslvr requested changes
Looks fine. Just found some missing "new" -> "translated" 🙂

2023-06-14 18:04 UTC, dtslvr commented on apps/client/src/locales/messages.pt.xlf
> +        <target state="new">Risco menos Elevado</target>
state="translated"

2023-06-14 18:04 UTC, dtslvr commented on apps/client/src/locales/messages.pt.xlf
> +        <target state="new">Risco mais Elevado</target>
state="translated"

2023-06-14 18:04 UTC, dtslvr commented on apps/client/src/locales/messages.pt.xlf
> +        <target state="new">Adicionar conta</target>
state="translated"

2023-06-14 22:41 UTC, luispinho commented
> Looks fine. Just found some missing "new" -> "translated" 🙂

Fixed 👍

2023-06-15 06:16 UTC, dtslvr approved these changes

2023-06-15 06:16 UTC, dtslvr commented
> Fixed 👍

Thank you @luispinho

2023-06-15 06:34 UTC, merged