Feature/Hide null average unit price in the detailed activity dialog
ghostfolio/ghostfolio pull request #2123
Opened 2023-07-05 18:53 UTC by bptrgx

If I sell out a position then buy it again, the chart in the detailed activity dialog shows a null average unit price, the line goes to zero. It makes the chart less readable. It would make more sens that the line is interrupted when the position was closed.

Now:
![Screenshot 2023-07-05 at 19-48-44 ${title}](https://github.com/ghostfolio/ghostfolio/assets/47859535/2590a2a3-203f-4f72-b542-7fc9dd2c4a9b)

With this PR:
![Screenshot 2023-07-05 at 19-48-56 ${title}](https://github.com/ghostfolio/ghostfolio/assets/47859535/29fad734-1062-4233-86a0-293f49c085a4)

2023-07-07 10:41 UTC, bptrgx commented on apps/client/src/app/components/position/position-detail-dialog/position-detail-dialog.component.ts
> +              if (historicalDataItem.averagePrice) {
Done: https://github.com/ghostfolio/ghostfolio/pull/2123/commits/0ed0e53d883562feebc1277da750e0b589941844

2023-07-07 16:22 UTC, dtslvr requested changes
Hi @bptrgx

I have just tested it with my data, but it's not working correctly yet. The modal freezes when the history is big enough.

[ghostfolio-export-BABA-202307071819.json.zip](https://github.com/ghostfolio/ghostfolio/files/11984039/ghostfolio-export-BABA-202307071819.json.zip)

`Array.fill()` seems to create too many `null` values where the browser is unable to cope at some point:

<img width="507" alt="average-unit-price-chart" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/37ce80cd-952b-498d-89fe-dd42f8e1bd09">

Can you please take a look?

2023-07-07 18:59 UTC, bptrgx commented
Hi @dtslvr

I added with this commit https://github.com/ghostfolio/ghostfolio/pull/2123/commits/946fd1471d394c4f212ad03981cd681e2df0cf43 a condition to avoid the creation of datasets with only null values.

2023-07-08 09:13 UTC, dtslvr commented
I've found a simpler way to achieve the same: https://github.com/ghostfolio/ghostfolio/pull/2133
What do you think @bptrgx?

2023-07-08 12:14 UTC, closed without merging