Feature/Toggle accounts visibility from accounts page
ghostfolio/ghostfolio pull request #2137
Opened 2023-07-09 17:23 UTC by bptrgx

When I want to toggle the visibility of an account, going through the create-or-update-account-dialog is too long (_burger menu -> edit -> "Exclude from Analysis" -> Save_). The visibility indicator (the crossed eye) should be a button that toggles the visibility of the account.

Now:
![Screenshot.png](https://github.com/ghostfolio/ghostfolio/assets/47859535/16693441-39a4-430b-a48f-0cff6e06f77b)

With this PR:
![Recording.gif](https://github.com/ghostfolio/ghostfolio/assets/47859535/909aa041-9087-4fd1-97b8-efe95864cd39)

2023-07-11 05:58 UTC, dtslvr requested changes
Thanks for your contribution @bptrgx. I have added some comments.

2023-07-11 05:58 UTC, dtslvr commented on apps/client/src/app/components/accounts-table/accounts-table.component.html
> +        <ion-icon
Can you wrap the icon into a button?

```
<button
  class="mx-1 no-min-width px-2"
  mat-button
  (click)="onToggleExcluded(element); $event.stopPropagation()"
>
  <ion-icon [name]="element.isExcluded ? 'eye-off-outline' : 'eye-outline'" [ngClass]="{ 'text-muted': !element.isExcluded }"></ion-icon>
</button>
```

2023-07-11 05:58 UTC, dtslvr commented on apps/client/src/app/components/accounts-table/accounts-table.component.scss
> +    #isExcluded-icon {
We don't use ids for styling. With my suggestion above, you don't need it at all.

2023-07-11 05:58 UTC, dtslvr commented on apps/client/src/app/components/accounts-table/accounts-table.component.ts
> +  public onToggleExcluded(aAccount: AccountModel) {
Can you move it down to keep the alphabetical order?

2023-07-11 05:58 UTC, dtslvr commented on apps/client/src/app/pages/accounts/accounts-page.component.ts
> +  public onToggleExcluded(aAccount: AccountModel) {
`onToggleExcludedAccount({accountType, balance, comment, ...}: AccountModel)`

2023-07-11 05:58 UTC, dtslvr commented on apps/client/src/app/pages/accounts/accounts-page.component.ts
> +      .putAccount(account)
```
.putAccount({
  accountType,
  balance,
  comment,
  ...
})
```

2023-07-26 10:07 UTC, bptrgx commented
Hi @dtslvr, I've made the changes you suggested.

2023-09-20 14:03 UTC, closed without merging