Update messages.it.xlf
ghostfolio/ghostfolio pull request #2325
Opened 2023-09-13 08:50 UTC by alfredonodo

Hi,
I have updated the Italian translation, it was a longer task than I expected :)
I revised my work, but there might be some mistakes. So from today I will use Ghostfolio in Italian and correct any errors (for example in some cases I am not sure if it is a command/action or a description/label).
For economic and financial terms, I used [this thread](https://forum.wordreference.com/threads/stock-shares-securities-options-equity.182011/).

2023-09-13 16:03 UTC, dtslvr requested changes
Can you set every state from "new" to "translated" please?

It general it looks good, thanks for your changes 😎
When you really use it, you will probably find smaller details, but these are quick fixes then.

2023-09-13 20:04 UTC, alfredonodo commented on apps/client/src/locales/messages.it.xlf
> +        <target state="new">alternativa-open-source-a</target>
Not sure here. I used the English string.

2023-09-13 20:06 UTC, alfredonodo commented
> Can you set every state from "new" to "translated" please?
> 
> It general it looks good, thanks for your changes 😎 When you really use it, you will probably find smaller details, but these are quick fixes then.

I changed new to translated and I used &Xgrave; for all accented letters.

2023-09-14 17:46 UTC, dtslvr approved these changes
> I changed new to translated and I used &Xgrave; for all accented letters.

Thank you @alfredonodo. Not sure if the encoding is really needed. It's just harder to read 😒

2023-09-14 17:48 UTC, merged

2023-09-14 18:39 UTC, alfredonodo commented
> > I changed new to translated and I used &Xgrave; for all accented letters.
> 
> Thank you @alfredonodo. Not sure if the encoding is really needed. It's just harder to read 😒

If you want, I can remove them with Find and Replace.

2023-09-15 17:27 UTC, dtslvr commented on apps/client/src/locales/messages.it.xlf
> +        <target state="new">alternativa-open-source-a</target>
`alternativa-open-source-a` was the correct one! 😳