Use port numbers from environment file.
ghostfolio/ghostfolio pull request #2406
Opened 2023-10-01 05:05 UTC by prashmohan

Allow overriding of the postgres and redis forwarded ports in the docker configuration to allow running on alternate ports where the default ports may already be in use.

2023-10-01 07:36 UTC, dtslvr requested changes

2023-10-01 07:36 UTC, dtslvr commented on docker/docker-compose.dev.yml
Can you please adopt the change(s) also to `docker-compose.yml` and `docker-compose.build.yml`?

2023-10-01 10:17 UTC, prashmohan commented on docker/docker-compose.dev.yml
docker-compose.yml and docker-compose.build.yml should not require any modification, since they do not export the postgres and redis ports on the host machine.

2023-10-03 11:30 UTC, dtslvr requested changes

2023-10-04 20:00 UTC, dtslvr commented
What do you think of my changes @prashmohan?

2023-10-05 05:47 UTC, prashmohan commented
> What do you think of my changes @prashmohan?

I dont think this change would work though. This is overriding the port number that postgres is listening on inside its container. Looking at the environment variables that postgres uses (in https://hub.docker.com/_/postgres), it does not appear that the postgres container can be configured to have the service listening on a different port. In this case, I assume the ghostfolio server will be unable to reach postgres.

The way I am intending to use the environment variable specified in ghostfolio's config is to configure the port being used on the host machine without tampering with the port configuration used within the containers.

2023-10-07 08:10 UTC, dtslvr commented
> I dont think this change would work though.

Thanks for your explanation @prashmohan. I have reverted my changes. Now, `${POSTGRES_PORT}` is only used (optionally) in `docker-compose.dev.yml`. You are free to define `POSTGRES_PORT` in your `.env` file. What do you think?

2023-10-07 11:52 UTC, prashmohan commented
> What do you think?

Yup. I think that works best for development.

2023-10-07 12:08 UTC, dtslvr approved these changes

2023-10-07 15:18 UTC, merged