refactor: use FormBuilder for account form
ghostfolio/ghostfolio pull request #2408
Opened 2023-10-01 06:14 UTC by thesanjeevsharma

Related to #2350 

I've made the changes to the Account form. Please let me know if the approach is correct and if the same needs to be done for other forms.

(I am react dev, touched angular after years 🙈 )

2023-10-01 09:28 UTC, dtslvr requested changes
This already looks very good @thesanjeevsharma. I have added a few comments.

2023-10-01 09:28 UTC, dtslvr commented on apps/client/src/app/pages/accounts/create-or-update-account-dialog/create-or-update-account-dialog.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: CreateOrUpdateAccountDialogParams,
Can you move up ⬆️ for an alphabetical order?

2023-10-01 09:28 UTC, dtslvr commented on apps/client/src/app/pages/accounts/create-or-update-account-dialog/create-or-update-account-dialog.component.ts
> +      name: [this.data.account.name, Validators.required]
Can you move up ⬆️ for an alphabetical order?

2023-10-01 09:28 UTC, dtslvr commented on apps/client/src/app/pages/accounts/create-or-update-account-dialog/create-or-update-account-dialog.html
>            disabled
This does not seem to work anymore. Can you adapt it for form control?

2023-10-01 09:28 UTC, dtslvr commented on apps/api/src/app/account/create-account.dto.ts
> +  accountType?: AccountType;
👍🏻

2023-10-01 09:28 UTC, dtslvr commented on apps/api/src/app/account/update-account.dto.ts
> +  accountType?: AccountType;
👍🏻

2023-10-02 04:42 UTC, thesanjeevsharma commented
@dtslvr Thanks for the review. I've addressed the comments.

2023-10-03 17:19 UTC, dtslvr approved these changes
Thank you @thesanjeevsharma for the changes. Looks fine now! I have made some minor improvements.

2023-10-03 17:34 UTC, merged