fix current version from AdminData #2424
ghostfolio/ghostfolio pull request #2427
Opened 2023-10-04 16:34 UTC by akshaywadatkar

fix the version bug for #2424

2023-10-04 18:51 UTC, dtslvr requested changes
Can you change `{{ version }}` to `<gf-value [value]="version" />` in the template (`admin-overview.component.html`)?

2023-10-04 18:51 UTC, dtslvr commented on apps/client/src/app/components/admin-overview/admin-overview.component.ts
> +  public version:any
`public version: string;`

2023-10-04 19:08 UTC, akshaywadatkar commented on apps/client/src/app/components/admin-overview/admin-overview.component.ts
> +  public version:any
sure

2023-10-07 06:50 UTC, dtslvr approved these changes

2023-10-07 07:11 UTC, merged