feat: use FormBuilder for access form
ghostfolio/ghostfolio pull request #2437
Opened 2023-10-05 19:33 UTC by thesanjeevsharma

Related to https://github.com/ghostfolio/ghostfolio/issues/2350

I've made the changes to the Access Form as well.

2023-10-07 07:29 UTC, dtslvr requested changes
Thanks for the PR @thesanjeevsharma. I have added some comments.

2023-10-07 07:29 UTC, dtslvr commented on apps/client/src/app/components/user-account-access/create-or-update-access-dialog/create-or-update-access-dialog.html
> +          <input
Add `(keydown.enter)="$event.stopPropagation()"`

2023-10-07 07:29 UTC, dtslvr commented on apps/api/src/app/access/create-access.dto.ts
> +  type?: string;
`type?: 'PUBLIC';`

2023-10-08 16:50 UTC, thesanjeevsharma commented
@dtslvr I've addressed the comments.

2023-10-09 17:11 UTC, merged