#2371 Issue : Migrated admin jobs table to mat-table
ghostfolio/ghostfolio pull request #2444
Opened 2023-10-07 11:39 UTC by Basimohd

I've migrated Jobs Table of Admin Control to mat-table. Could you kindly review and confirm if this approach aligns with the desired implementation?

2023-10-08 17:50 UTC, dtslvr requested changes
That looks fine, @Basimohd! 👍🏻 

Just one comment and a little problem with the formatting in `admin-jobs.module.ts` (space in `{ }`) 🙂

2023-10-08 17:50 UTC, dtslvr commented on apps/client/src/app/components/admin-jobs/admin-jobs.html
> +            <ng-container>#</ng-container>
When there is no `i18n` directive, you don't need `<ng-container>`. Can you remove it?

2023-10-09 06:21 UTC, dtslvr approved these changes

2023-10-09 09:32 UTC, Basimohd commented
@dtslvr should I do the formatting?

2023-10-09 09:36 UTC, Basimohd commented
@dtslvr I have noticed that one checks failed on formatting.Should I have to fix it?

2023-10-09 17:38 UTC, merged