Feature/#2440 : Created membership card component and Inegrated it to AboutOverviewPageComponent
ghostfolio/ghostfolio pull request #2507
Opened 2023-10-18 10:04 UTC by Basimohd

#2440 : I've IntegratedCreated membership card component and Inegrated it to AboutOverviewPageComponent. Could you kindly review and confirm if this approach aligns with the desired implementation?

2023-10-18 15:49 UTC, dtslvr requested changes
Nice addition! 👍🏻 I have added some feedback.

2023-10-18 15:49 UTC, dtslvr commented on libs/ui/src/lib/membership-card/membership-card.component.scss
> +    margin-left: auto;
I think you can use `mx-auto` in the template

2023-10-18 15:49 UTC, dtslvr commented on libs/ui/src/lib/membership-card/membership-card.component.scss
> +    line-height: 1;
I think you can use `line-height-1` in the template

2023-10-18 15:49 UTC, dtslvr commented on libs/ui/src/lib/membership-card/membership-card.module.ts
> +export class GFMembershipCardModule {}
`GfMembershipCardModule`

2023-10-19 04:37 UTC, Basimohd commented
@dtslvr  I have resolved all the concerns outlined in the comments.

2023-10-19 20:13 UTC, dtslvr approved these changes
Great work, @Basimohd! 🙌🏻 

<img width="1064" alt="membership" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/f4b3cf9a-0397-4249-a4a5-0266710df911">

2023-10-20 03:39 UTC, Basimohd commented
@dtslvr Thank you!😊 I'm eager to make even more contributions!

2023-10-20 06:18 UTC, merged