feat: extend asset profile dialog form
ghostfolio/ghostfolio pull request #2535
Opened 2023-10-22 14:22 UTC by Dhoni77

Closes #2524

- Added name (required), assetClass and assetSubClass inputs.
- Handled the form data in frontend and backend.

Attachment:

![asset_dialog](https://github.com/ghostfolio/ghostfolio/assets/53973174/f0423dd1-7a56-454c-adfa-10dbfb10080f)

2023-10-24 18:10 UTC, dtslvr requested changes
Thanks again, @Dhoni77! 😎 I have added some comments.

2023-10-24 18:10 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html
> +          [hidden]="!assetProfileClass"
`[hidden]="!assetProfileForm.controls['assetClass'].value"`

2023-10-24 18:10 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html
> +          [value]="assetProfileClass"
`[value]="assetProfileForm.controls['assetClass'].value"`

2023-10-24 18:10 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html
> +          [hidden]="!assetProfileSubClass"
`[hidden]="!assetProfileForm.controls['assetSubClass'].value"`

2023-10-24 18:10 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html
> +          [value]="assetProfileSubClass"
`[value]="!assetProfileForm.controls['assetSubClass'].value"`

2023-10-25 04:48 UTC, Dhoni77 commented
cc @dtslvr

2023-10-25 18:11 UTC, dtslvr approved these changes
Thank you for the modifications, @Dhoni77! 👍🏻 
Ready to merge now.

2023-10-25 18:28 UTC, merged