feat: extend benchmark endpoint by trend50d and trend200d
ghostfolio/ghostfolio pull request #2575
Opened 2023-11-01 16:54 UTC by Dhoni77

Closes #2567

- Calculate benchmark trends for trend50d and trend200d
- Added interface and type

2023-11-01 16:56 UTC, Dhoni77 commented
Hi @dtslvr could you please check if the expected logic is correct in the above pr.
If so I would further refactor the code.
Thanks

2023-11-02 19:41 UTC, dtslvr requested changes
Thanks for providing this draft, @Dhoni77.

I have added `^GSPC` as _Market Data_ in the _Admin Control_ panel, gathered historical data and checked the results against these [moving averages](https://www.barchart.com/stocks/quotes/$SPX/technical-analysis) (red for `DOWN`, green for `UP`). The values match 😎

In the first request, one value of `50d` and `200d` was `null`, after reloading the endpoint, both values were there. Have you seen this behaviour before?

I have already added some comments for the refactoring. If you are interested, you are invited to write a test for the moving average function in a follow-up task.

Thank you once again for your dedication!

2023-11-02 19:41 UTC, dtslvr commented on apps/api/src/app/benchmark/benchmark.service.ts
> +  public async getBenchMarkTrends(dataSource: DataSource, symbol: string) {
Please use `benchmark` instead of `benchMark` 😛

2023-11-02 19:41 UTC, dtslvr commented on apps/api/src/app/benchmark/benchmark.service.ts
> +    return this.marketDataService
`const historicalData = await this.marketDataService...` instead of chaining

2023-11-02 19:41 UTC, dtslvr commented on apps/api/src/app/benchmark/benchmark.service.ts
> +        const fiftyDayAvg = calculateBenchmarkTrend(historicalData, 50);
`Average` instead of `Avg`

2023-11-02 19:41 UTC, dtslvr commented on apps/api/src/app/benchmark/benchmark.service.ts
> +            date: allTimeHigh?.date || new Date(),
`??` instead of `||`

2023-11-02 19:41 UTC, dtslvr commented on libs/common/src/lib/types/benchmark-trend-type.type.ts
Can you add it to `libs/common/src/lib/types/index.ts`?

2023-11-03 07:47 UTC, Dhoni77 commented
> Thanks for providing this draft, @Dhoni77.
> 
> I have added `^GSPC` as _Market Data_ in the _Admin Control_ panel, gathered historical data and checked the results against these [moving averages](https://www.barchart.com/stocks/quotes/$SPX/technical-analysis) (red for `DOWN`, green for `UP`). The values match 😎
> 
> In the first request, one value of `50d` and `200d` was `null`, after reloading the endpoint, both values were there. Have you seen this behaviour before?
> 
> I have already added some comments for the refactoring. If you are interested, you are invited to write a test for the moving average function in a follow-up task.
> 
> Thank you once again for your dedication!

Hi @dtslvr, If we need to calcuate the 50day trend we need the data for last 100 days and for 200d trend we need data for 400 days. So if data is not present I am returning null. Is this correct ?

2023-11-03 13:15 UTC, dtslvr commented
> Is this correct ?

Yes, that makes sense. I think data was already there, but still got `null`.

2023-11-15 19:24 UTC, dtslvr approved these changes

2023-11-15 19:25 UTC, merged