feat: improve historical market data import
ghostfolio/ghostfolio pull request #2581
Opened 2023-11-03 14:10 UTC by Dhoni77

Closes #2521 

- [x] Create a dedicated form group for the historical market data import
- [x] Consider the [default value](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts#L55) as "invalid" (disable the Import button)
- [x] Wrap csvToJson and parseDate() in one try / catch block and show a [snackbar](https://material.angular.io/components/snack-bar) on error
- [x] Remove the current [placeholder](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html#L64)

2023-11-04 09:11 UTC, dtslvr commented
Still a draft @Dhoni77?

2023-11-05 13:29 UTC, Dhoni77 commented
> Still a draft @Dhoni77?

cc @dtslvr

2023-11-06 17:30 UTC, dtslvr requested changes
Thank you for creating this PR, @Dhoni77! 😎

_Consider the [default value](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts#L55) as "invalid" (disable the Import button)_ does not seem to be implemented yet, is it?

Additionally, I have added some comments. Can you please have a look?

2023-11-06 17:30 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +    historicalData: this.formBuilder.group({
Please move up ⬆️

2023-11-06 17:30 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +          historicalData: {
Please move up ⬆️

2023-11-06 17:30 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +        .pipe(takeUntil(this.unsubscribeSubject))
Can you add
```
catchError(({error, message}) => {
  this.snackBar.open(`${error}: ${message[0]}`, undefined, { duration: 3000 });
  return EMPTY;
})
```

2023-11-06 17:30 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +      this.snackBar.open('Unable to parse data', undefined, { duration: 3000 });
Please change to
```
this.snackBar.open($localize`Oops! Could not parse historical data`, undefined, { duration: 3000 });
```

2023-11-06 17:30 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +    } catch (err) {
Just `} catch {`

2023-11-06 17:30 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html
> +        [disabled]="assetProfileForm.controls['symbolMapping']?.value === ''"
Should be `historicalData` instead of `symbolMapping`

2023-11-07 04:26 UTC, Dhoni77 commented
cc @dtslvr

2023-11-07 16:14 UTC, dtslvr approved these changes
Thanks for the improvement, @Dhoni77! 🙌🏻

Ready to merge now.

2023-11-07 17:16 UTC, merged