Holdings extended by Dividend Yield Percentage
ghostfolio/ghostfolio pull request #2636
Opened 2023-11-11 12:24 UTC by Fullstack-Arshad

Feature: #2533

2023-11-11 12:26 UTC, Fullstack-Arshad commented
Hi @dtslvr, I have used overall dividend to calculate dividend percentage, let me know if any other change is required :)

2023-11-11 12:28 UTC, Fullstack-Arshad commented
do you want me to add ok-dividend json file as well

2023-11-18 15:26 UTC, Fullstack-Arshad commented
Hi @dtslvr , is there any other change require? Let me know please

2023-11-20 18:01 UTC, dtslvr requested changes
Thank you for your contribution, @Fullstack-Arshad! 🙂
I have added a few comments.

2023-11-20 18:01 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +        (dividendInBaseCurrency.toNumber() * 100) / marketPrice;
Can you refactor the calculation using `Big.js`?

```
dividendInBaseCurrency.mul(100).div(marketPrice);
```

2023-11-20 18:01 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +        dividendYieldInPercent: dividendYieldInPercent,
`dividendYieldInPercent: dividendYieldInPercent.toNumber();`

2023-11-21 13:57 UTC, Fullstack-Arshad commented on apps/api/src/app/portfolio/portfolio.service.ts
> +        dividendYieldInPercent: dividendYieldInPercent,
done. Please Check

2024-01-03 18:49 UTC, Joren-vanGoethem commented
this is a feature i would really like to see, should we fork it and re-open the merge so that we can actually merge it since it seems like he is inactive on github now...

2024-01-08 15:16 UTC, Joren-vanGoethem commented
> I am there, is there still something pending? @dtslvr said code is ready to merge now, I was under the impression that it is completed. I can continue if anything is required.

you need to actually initiate the merge i think, unless @dtslvr can do it

2024-01-08 15:35 UTC, dtslvr commented
> you need to actually initiate the merge i think

This PR is fine from a technical point of view. Currently, there are a few things changing in the performance calculation, so I wanted to wait with the integration. In the meantime, I have realized that the calculation with all-time dividend is probably too simple and needs to be annualized. What do you think?

2024-01-09 03:22 UTC, Fullstack-Arshad commented
Yes I felt the same while Implementing this

2024-01-09 07:11 UTC, dtslvr commented
> Yes I felt the same while Implementing this

There is a `getAnnualizedPerformancePercent()` function in [PortfolioCalculator](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio-calculator.ts#L156). Maybe that would be enough?

2024-01-27 18:01 UTC, Fullstack-Arshad commented
I am sorry I didn't get you @dtslvr, in order to calculate dividend yield percentage I need annualized dividend, How can I get annualized dividend using getAnnualizedPerformancePercent(). Can you please explain bit more.

2024-01-28 08:58 UTC, dtslvr commented
You currently calculate the (total) dividend yield with the sum of all dividend. My idea is to annualize (normalization) this dividend yield with the number of days you are holding this position (via date of first activity) using `getAnnualizedPerformancePercent()`.

2024-04-03 17:47 UTC, merged