Feat: Extended market data with preset by activitiesCount and date
ghostfolio/ghostfolio pull request #3022
Opened 2024-02-18 16:18 UTC by bikash-789

<img width="1792" alt="Screenshot 2024-02-18 at 21 28 03" src="https://github.com/ghostfolio/ghostfolio/assets/63906998/7061e345-f225-4b1f-ba80-9ff544fde5d6">

I've added attributes `activitesCount` and `date`(First Activity) on the market data with `presetId` = `CURRENCIES` as you can see in the screenshot. Let me know if I need to make any changes.

2024-02-19 13:51 UTC, dtslvr commented
Thank you for the pull request, @bikash-789. I will review as soon as possible.

2024-02-20 19:26 UTC, dtslvr requested changes
I have tested the code, but it does not seem to work.

`activityCount` is always 0. It does not count the number of orders per currency (part of `SymbolProfile`).

`date` is `undefined`, therefore `earliestDate` is always the current date.

Would you like to give it another try?

2024-02-21 08:42 UTC, bikash-789 commented
@dtslvr Thanks for the suggestion. I will work on it.

2024-07-20 15:41 UTC, dtslvr commented
Superseded by https://github.com/ghostfolio/ghostfolio/pull/3460.

2024-07-20 15:41 UTC, closed without merging