Updated historical data import
ghostfolio/ghostfolio pull request #3117
Opened 2024-03-08 20:00 UTC by helgehatt

Send date strings as is and let server handle parsing

Fixes an issue where e.g. "2017-01-01" is sent as "2016-12-31T23:00:00.000Z"

Closes #3116

2024-03-09 10:16 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +      ).data as { date: string; marketPrice: number }[];
`as UpdateMarketDataDto[]`

2024-03-09 10:18 UTC, dtslvr requested changes
Thanks for your contribution, @helgehatt.

Can you do the same [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data-detail/market-data-detail-dialog/market-data-detail-dialog.component.ts#L60) as well?

2024-03-09 10:40 UTC, helgehatt commented
@dtslvr Happy to help. In this case the date is a `Date` object, so we have to convert it to string in one way or another. Do you know if this method also causes issues?

2024-03-09 11:37 UTC, dtslvr commented
> @dtslvr Happy to help. In this case the date is a `Date` object, so we have to convert it to string in one way or another. Do you know if this method also causes issues?

Isn't it the same because `toISOString()` is also called (`this.data.date.toISOString()`)❓
The functionality is broken (same as import but used to edit a single entry via GUI).

2024-03-10 00:18 UTC, helgehatt commented
> > @dtslvr Happy to help. In this case the date is a `Date` object, so we have to convert it to string in one way or another. Do you know if this method also causes issues?
> 
> Isn't it the same because `toISOString()` is also called (`this.data.date.toISOString()`)❓ The functionality is broken (same as import but used to edit a single entry via GUI).

Converting from `Date` to string should be fine. The problem is when you convert from string to a `Date` object. That’s when timezone issues arise. So to achieve the same thing here, we would have to modify `date` in the interface to be of type string and avoid the conversion to `Date` in the first place.

https://github.com/ghostfolio/ghostfolio/blob/ba73f6de2e3019c1803d9e5fa45fca66d80bb618/apps/client/src/app/components/admin-market-data-detail/market-data-detail-dialog/interfaces/interfaces.ts#L5-L12

Alternatively, instead of avoiding conversion we can try to fix the conversion. Obviously the `parseDate` function used in the `AssetProfileDialog.onImportHistoricalData` method is giving unexpected results. Do you know how to debug the client side code? Much easier to bugfix when you can see the values of all variables.

2024-03-10 08:50 UTC, dtslvr commented
>  ...to achieve the same thing here...

I don't think there is any difference as they share the same endpoint which consumes `ISO8601` (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.controller.ts#L249)). In one case, the user inputs a date as `CSV` (parse date locally) and in the other case the date comes from a date picker (local date).

> Do you know how to debug the client side code?

You can either use the developer tools of your browser or `console.log()` statements.

2024-03-10 14:50 UTC, helgehatt commented
So the latest changes is how it looks like if we do the same in both cases and avoid conversion to `Date` altogether.

2024-03-13 19:32 UTC, dtslvr approved these changes
Thanks for your contribution, it looks pretty simple like this 🙂
Ready to merge now.

2024-03-13 19:44 UTC, merged