Bugfix/fix state of currency selector component (#2795)
ghostfolio/ghostfolio pull request #3429
Opened 2024-05-23 17:17 UTC by SirZemar

* Fix state of currency selector component

2024-05-23 18:34 UTC, dtslvr requested changes
Nice. Looks a bit cleaner now 👍🏻 There is one suggestion for refactoring in the template.

2024-05-23 18:34 UTC, dtslvr commented on libs/ui/src/lib/currency-selector/currency-selector.component.html
>    @for (currencyItem of filteredCurrencies; track currencyItem) {
`@for (currency of filteredCurrencies; track currency) {`

2024-05-23 18:34 UTC, dtslvr commented on libs/ui/src/lib/currency-selector/currency-selector.component.html
> +      {{ currencyItem }}
`{{ currency }}`

2024-05-29 11:34 UTC, dtslvr commented
@SirZemar have you seen my feedback?

2024-05-31 15:27 UTC, SirZemar commented
I will take care of it, thank you @dtslvr for calling out to my attention.

2024-06-01 07:59 UTC, dtslvr approved these changes
Thank you for the changes, @SirZemar!

While testing I found an issue in the account dialog and fixed it via https://github.com/ghostfolio/ghostfolio/pull/3429/commits/aca6ccdb60c95f649fd70f46d01f29d62ce3815d. Ready to merge now.

2024-06-01 08:53 UTC, merged