Replaced the usage of alert() with MatDialog
ghostfolio/ghostfolio pull request #3670
Opened 2024-08-13 04:03 UTC by dinirichard

Every instance of alert() was replaced with notification service

2024-08-13 06:13 UTC, dtslvr requested changes
Thank you for working on this issue, @dinirichard 👍🏻 I have added a few comments.

2024-08-13 06:13 UTC, dtslvr commented on apps/client/src/app/app.component.ts
> +    private notificationService: NotificationService
Can you please move up ⬆️ to keep the alphabetical order?

2024-08-13 06:13 UTC, dtslvr commented on apps/client/src/app/app.component.ts
> +      this.notificationService.alert({
I would set the `message` as `title` (to avoid `title: ''`)

2024-08-13 06:13 UTC, dtslvr commented on apps/client/src/app/components/header/header.component.ts
> +                this.notificationService.alert({
```
this.notificationService.alert({
  title: $localize`Oops! Incorrect Security Token.`
});
```

2024-08-13 06:13 UTC, dtslvr commented on apps/client/src/app/components/user-account-access/create-or-update-access-dialog/create-or-update-access-dialog.component.ts
> +                title: 'Bad Request',
Remove title

2024-08-13 06:13 UTC, dtslvr commented on apps/client/src/app/components/user-account-membership/user-account-membership.component.ts
> +            title: result.error.type,
Remove title

2024-08-13 06:13 UTC, dtslvr commented on apps/client/src/app/pages/pricing/pricing-page.component.ts
> +            title: result.error.type,
Remove title

2024-08-13 06:13 UTC, dtslvr commented on package-lock.json
Can you please revert this change?

2024-08-14 08:34 UTC, dtslvr requested changes
Thanks for implementing the changes. I have added a few more comments.

2024-08-14 08:34 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts
> +            title: `Error: ${error?.message}`
```
this.notificationService.alert({
  message: error?.message,
  title: $localize`Error`
});
```

Sorry if I have changed my mind here.

2024-08-14 08:34 UTC, dtslvr commented on apps/client/src/app/components/admin-overview/admin-overview.component.ts
> +    private notificationService: NotificationService
Move up ⬆️

2024-08-14 08:34 UTC, dtslvr commented on apps/client/src/app/components/user-account-membership/user-account-membership.component.ts
> +            title: error
```
title: error.message
```

2024-08-14 08:34 UTC, dtslvr commented on apps/client/src/app/components/user-account-membership/user-account-membership.component.ts
>            throw error;
Add line break

2024-08-14 08:34 UTC, dtslvr commented on apps/client/src/app/pages/pricing/pricing-page.component.ts
> +            title: error
```
title: error.message
```

2024-08-14 08:34 UTC, dtslvr commented on apps/client/src/app/pages/pricing/pricing-page.component.ts
>            throw error;
Add line break

2024-08-14 10:39 UTC, dinirichard commented on apps/client/src/app/pages/pricing/pricing-page.component.ts
>            throw error;
Sorry but I don't understand

2024-08-14 16:03 UTC, dtslvr commented on apps/client/src/app/pages/pricing/pricing-page.component.ts
>            throw error;
Insert an empty line 🙂

```
this.notificationService.alert({
  title: error
});
          
throw error;
```

2024-08-15 07:41 UTC, dtslvr approved these changes
Thanks again, @dinirichard!

Ready to merge now.

2024-08-15 09:36 UTC, merged