Add currency to create asset profile dialog #3773
ghostfolio/ghostfolio pull request #3819
Opened 2024-09-25 18:50 UTC by madhab-chandra-sahoo

**[Feature] Integrate add currency into create asset profile dialog #3773**

<img width="1721" alt="Screenshot 2024-09-25 at 11 37 18 PM" src="https://github.com/user-attachments/assets/9c22f20c-ef90-4978-a890-b37efe7f4082">

<img width="1727" alt="Screenshot 2024-09-25 at 11 37 43 PM" src="https://github.com/user-attachments/assets/4fab688a-68a8-4682-b69a-f5e64f5d15ce">

<img width="1727" alt="Screenshot 2024-09-25 at 11 38 11 PM" src="https://github.com/user-attachments/assets/af56e8e1-b604-40e5-8f56-df1f37637316">

<img width="1727" alt="Screenshot 2024-09-26 at 12 20 16 AM" src="https://github.com/user-attachments/assets/1cc3456d-b112-400e-a57c-81582f7d7108">

2024-09-26 17:03 UTC, dtslvr requested changes
Thank you for your contribution, @madhab-chandra-sahoo! 🙂
I have added a few comments.

2024-09-26 17:03 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts
> +      if (currency.length === 3) {
Add line break

2024-09-27 06:11 UTC, madhab-chandra-sahoo commented
@dtslvr Thanks for the review. I've updated the code as per your suggestions, Please recheck.

2024-09-27 18:14 UTC, dtslvr requested changes
Thanks a lot for the update! 🤓
I have reviewed again and added a few comments. The issue is almost complete.

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts
> +    private changeDetectorRef: ChangeDetectorRef,
Please add `readonly`

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.html
> +            *ngIf="
Please use the new control flow syntax:

```
@if (createAssetProfileForm.get('addCurrency').hasError('required')) {
  <mat-error i18n>Currency is required.</mat-error>
}
```

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.html
> +          <mat-error *ngIf="showCurrencyErrorMessage" i18n>
Please use the new control flow syntax

2024-09-27 18:14 UTC, dtslvr commented on package.json
> +  "version": "2.111.0",
Please keep at `2.110.0`, the version will be increased in the release process 🙂

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts
> +    } else {
`} else if (this.mode === 'currency') {`

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts
> +  get showCurrencyErrorMessage() {
```
public get showCurrencyErrorMessage() {
```

Please also move up to the other public functions

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts
> +    if (
Add line break

2024-09-27 18:14 UTC, dtslvr commented on apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts
> +    return false;
Add line break

2024-09-28 07:41 UTC, dtslvr approved these changes
Thanks again, @madhab-chandra-sahoo!
Ready to merge now 😎

2024-09-28 07:42 UTC, merged