Feature/add business logic of rule settings
ghostfolio/ghostfolio pull request #3826
Opened 2024-09-27 03:36 UTC by shaun-ak

PR for #3772

2024-09-28 09:26 UTC, dtslvr requested changes
Thank you for your contribution, @shaun-ak!

I have added a few comments. To test, you could customize _Threshold Max_ in _Fee Ratio_ to `0.05` and it should update the text to _The fees do not exceed 5% of your initial investment (0.00%)_.

2024-09-28 09:26 UTC, dtslvr commented on apps/client/src/app/components/rule/rule.component.ts
>          ({ settings }: { settings: PortfolioReportRule['settings'] }) => {
My bad, I get a deconstruction error here. Can you please change to

```
(settings: PortfolioReportRule['settings']) => {
```

2024-09-28 09:26 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
Can you change the line

```
(click)="dialogRef.close({ settings })"
```

to 
```
(click)="dialogRef.close(settings)"
```

2024-09-28 09:26 UTC, dtslvr commented on apps/api/src/app/user/update-user-setting.dto.ts
> +  portfolioSettings?: PortfolioReportRule['settings'];
Attention: data needs to be stored on `xRayRules` to make it work

You could adapt `RuleSettings` in `XRayRulesSettings` to something like this:

```
interface RuleSettings extends Pick<PortfolioReportRule, 'settings'> {
  isActive: boolean;
}
```

2024-09-28 09:26 UTC, dtslvr commented on apps/client/src/app/components/rule/rule.component.ts
> +              portfolioSettings: {
Change to something like this

```
xRayRules: {
  [rule.key]: settings
}
```

2024-09-28 09:26 UTC, dtslvr commented on apps/client/src/app/components/rule/rule.component.ts
> +            this.ruleUpdated.emit(updatedSettings);
Add line break

2024-09-29 04:50 UTC, shaun-ak commented
Hey @dtslvr , I tried to test it but the text does not change, however the correct object is emitted, I guess we need to update something on the api end?

2024-09-30 19:03 UTC, dtslvr approved these changes
> Hey @dtslvr , I tried to test it but the text does not change, however the correct object is emitted, I guess we need to update something on the api end?

Thank you for the contribution, @shaun-ak! 😎

I was able to finalize it, the only missing piece was providing the persisted setting (see [here](https://github.com/ghostfolio/ghostfolio/pull/3826/commits/b884ae3599ca174b22c9d2385cd827a700184eb3#diff-3c888bd2feb1b3eb21c716ab7d3ee77c3679a32922d79882b533dbfc211a6c31R83)).

Ready to merge now.

2024-10-01 17:13 UTC, merged