[BUG] Despite different language setting: Ghostfolio only shows English after login #3802
ghostfolio/ghostfolio pull request #3828
Opened 2024-09-27 08:49 UTC by madhab-chandra-sahoo

Fix: Fetched logged-in user settings to display in the preferred language

[Language bug solved](https://www.awesomescreenshot.com/video/31976064?key=d2ba517f6e5df3f5d7cff26587320d30)

2024-09-28 09:32 UTC, madhab-chandra-sahoo commented
Hi @dtslvr, can you please review this PR?

2024-09-28 15:44 UTC, dtslvr requested changes
Thanks for the contribution, @madhab-chandra-sahoo! 🙌🏻

I have added a few comments to align it with a similar implementation in the project (`UserAccountSettingsComponent`).

2024-09-28 15:44 UTC, dtslvr commented on apps/client/src/app/components/header/header.component.ts
> +    console.log('Set Token called');
Please remove

2024-09-28 15:44 UTC, dtslvr commented on apps/client/src/app/components/header/header.component.ts
> +      .get(true)
`.get()`

2024-09-28 15:44 UTC, dtslvr commented on apps/client/src/app/components/header/header.component.ts
> +      .subscribe((data) => {
`.subscribe((user) => {`

2024-09-28 15:44 UTC, dtslvr commented on apps/client/src/app/components/header/header.component.ts
> +        const userLanguage = data.settings.language;
Replace the full block with

```
const userLanguage = user?.settings?.language;

if (userLanguage && document.documentElement.lang !== userLanguage) {
  window.location.href = `../${userLanguage}`;
} else {
  this.router.navigate(['/']);
}
```

2024-09-28 15:44 UTC, dtslvr commented on apps/client/src/app/app.component.ts
Please revert all changes in this file (not needed)

2024-09-28 15:44 UTC, dtslvr commented on apps/client/src/app/components/home-overview/home-overview.component.ts
> -import { DateRange } from '@ghostfolio/common/types';
👀

2024-10-08 05:55 UTC, dtslvr commented
@madhab-chandra-sahoo Thanks for submitting the PR! I have reviewed it and left some comments with requested changes. Once those are addressed, feel free to ping me again, and I’ll be happy to take another look.

2024-10-08 18:14 UTC, madhab-chandra-sahoo commented
@dtslvr will resolve the comments by tomorrow

2024-10-10 17:59 UTC, madhab-chandra-sahoo commented on apps/client/src/app/components/home-overview/home-overview.component.ts
> -import { DateRange } from '@ghostfolio/common/types';
It was unused, so I removed it.

2024-10-10 18:00 UTC, madhab-chandra-sahoo commented
@dtslvr Please review the changes as suggested

2024-10-11 17:59 UTC, merged