feat: set up stylisticTypeChecked rule in eslint configuration
ghostfolio/ghostfolio pull request #3878
Opened 2024-10-05 17:39 UTC by dw-0

Fixes #3877 

Draft, once this is clearified:
>I have a question to this rule: https://typescript-eslint.io/rules/naming-convention/
>It is currently completely disabled. Is this intended? Should it stay disabled?

_Originally posted by @dw-0 in https://github.com/ghostfolio/ghostfolio/issues/3877#issuecomment-2395105096_

Within the scope of this PR, i also added some more type and style checks to the tsconfig files. I think those make sense as well, i hope that was okay and does not require another PR. But since i made it its own commit, it wouldn't be a big issue to extract it into a new PR.

What i noticed when i worked on this PR is, that for some reason the linting can indeed take quite a long time even though the cache was already built. Especially when squashing commits, it seems like the cache is ignored. Maybe we really want to look into linting only staged files, this should speed up the overall linting quite a lot. The build action could then run the full lint check on new PRs (would require a new ticket for this).

Signed-off-by: Dominik Willner <th33xitus@gmail.com>

2024-10-05 19:33 UTC, dw-0 commented
@dtslvr I reenabled the `@typescript-eslint/naming-convention` rule and set it to warn. I think i defined a feasable naming convention for this project. But please doublecheck and see if there is any nogo present. Set the rule to "error" and run a lint. Then you will see all the things that do not match the defined naming convention. It is quite a lot, so you decide if we apply this rule as is, tweak the naming convention or keep it disabled.

2024-10-06 08:56 UTC, dtslvr commented
> I reenabled the `@typescript-eslint/naming-convention` rule and set it to warn.

Hmm, there are a lot of them. Not sure if we can ever fix them (e.g. the included resources from _Prisma_ are all in pascal case and considered a problem). Probably better setting it to `off` at the moment. Currently it is quite distracting to see all the warnings in the code.

2024-10-06 09:02 UTC, dtslvr requested changes

2024-10-06 09:02 UTC, dtslvr commented on tsconfig.base.json
> +    // set to true to enable stricter type checking for this project
`"strict": false, // TODO: Enable stricter type checking for this project`

2024-10-06 09:02 UTC, dtslvr commented on apps/client/tsconfig.json
> +    "strictTemplates": false // todo: enable strict templates
`"strictTemplates": false // TODO: Enable strict templates`

2024-10-06 09:11 UTC, dw-0 commented
> Hmm, there are a lot of them. Not sure if we can ever fix them (e.g. the included resources from _Prisma_ are all in pascal case and considered a problem). Probably better setting it to `off` at the moment. Currently it is quite distracting to see all the warnings in the code.

I agree, we could keep the definition i created but simply turn it off as you suggest. In the end, the naming convention doesn't really do anything, it's not like it makes the code more robust or safer, its purely aesthetic.

2024-10-06 14:21 UTC, dtslvr approved these changes

2024-10-06 14:57 UTC, merged