[Feature] Set up unit test that loads activity from exported json file #3807
ghostfolio/ghostfolio pull request #3901
Opened 2024-10-10 15:12 UTC by dhaneshwaritendle

![image](https://github.com/user-attachments/assets/a4299368-77f9-43aa-a2f9-0fc1904c7cc1)

-Created file portfolio-calculator-dynamic-buy-and-sell.spec.ts  which is in directory apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts

-It checks for the 'activities' in which json data is parsed 

-It passed the test suites 

If I have missed something I would be happy to rectify it.

2024-10-10 18:27 UTC, dtslvr requested changes
Thank you for the contribution, @dhaneshwaritendle! I have added a few comments.

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +  activityDummyData,
Please remove unused import

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +  symbolProfileDummyData,
Please remove unused import

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +import path = require('path');
Please import like this:
```
import { join } from 'path';
```

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +import * as fs from 'fs';
Please import like this:
```
import { existsSync, readFileSync } from 'fs';
```

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +  let parsedData;
`let activities;`

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +  let parsedData;
Add line break

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +    parsedData = JSON.parse(jsonData);
`activities = JSON.parse(jsonData).activities;`

2024-10-10 18:27 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +  describe('get current positions', () => {
Add line break

2024-10-11 04:29 UTC, dhaneshwaritendle commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-dynamic-buy-and-sell.spec.ts
> +  describe('get current positions', () => {
on it!

2024-10-11 18:51 UTC, dtslvr approved these changes
Great work, @dhaneshwaritendle! 👌🏻
I have extracted the functionality to load the json file to a helper.
Ready to merge now.

2024-10-11 19:11 UTC, merged