feat: split holdings in chart dynamically
ghostfolio/ghostfolio pull request #3938
Opened 2024-10-16 11:14 UTC by vitalymatyushik

Address [the issue](https://github.com/ghostfolio/ghostfolio/issues/3931) and split the datapoints on treemap in 9 groups from red[9] to green[9] colors based on _netPerformancePercentWithCurrencyEffect_

2024-10-17 12:31 UTC, dtslvr requested changes
Thank you for this contribution, @vitalymatyushik! 😎
I have reviewed the changes and added a few comments.

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +      getAnnualizedPerformancePercent({
Please use the explicit version:
```
{
  return getAnnualizedPerformancePercent({ ... }).toNumber();
}
```

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +    const netPerformancePercentsWithCurrencyEffect = this.holdings.map((h) =>
```
const netPerformancePercentsWithCurrencyEffect = this.holdings.map(({ dateOfFirstActivity, netPerformancePercentWithCurrencyEffect }) =>
```

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +    const positiveNetPercents = netPerformancePercentsWithCurrencyEffect.filter(
`const positiveNetPerformancePercents = ...`

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +      (v) => v > 0
```
(v) => { return v > 0; }
```

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +    const positiveNetPercentsRange = {
Add a line break and refactor to

`const positiveNetPerformancePercentsRange = ...`

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +    const negativeNetPercents = netPerformancePercentsWithCurrencyEffect.filter(
Add a line break and refactor to

```
const negativeNetPerformancePercents = ...
```

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +      (v) => v < 0
```
{ return v < 0; }
```

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +    const negativeNetPercentsRange = {
Add a line break and refactor to

```
const negativeNetPerformancePercentsRange = ...
```

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> -
Revert please 🙂

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +            if (annualizedNetPerformancePercentWithCurrencyEffect > 0) {
`} else if (...) {` ❓

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +              if (
Add line breaks...

2024-10-17 12:31 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
>                return red[7];
`red[5]` ❓

2024-10-17 18:39 UTC, vitalymatyushik commented
thank you @dtslvr!
I've addressed the comments.

2024-10-19 08:25 UTC, dtslvr approved these changes
Thank you for this contribution, @vitalymatyushik! 🎉
Ready to merge.

2024-10-19 08:39 UTC, merged

2024-10-19 08:41 UTC, dtslvr commented
I have created a follow-up issue for the font color assignment: https://github.com/ghostfolio/ghostfolio/issues/3952