feat: add emerging markets rule
ghostfolio/ghostfolio pull request #3949
Opened 2024-10-18 20:42 UTC by vitalymatyushik

Add "Emerging Markets" rule

![image](https://github.com/user-attachments/assets/85123acf-bc4c-4747-b69b-7b09935ba507)

2024-10-19 12:52 UTC, dtslvr requested changes
Thanks for this contribution, @vitalymatyushik! 😎

As this is the first rule with `thresholdMin` and `thresholdMax`, it is a bit more tricky. I have added a few comments and hope that clarifies it.

2024-10-19 12:52 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +                  new AllocationClusterRiskEmergingMarkets(
Move to a new section:
`allocationClusterRisk: summary.ordersCount > 0 ? await this.rulesService.evaluate([ ... ])`

2024-10-19 12:52 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +    const { accounts, holdings, summary, markets } = await this.getDetails({
Reorder alphabetically please:
`const { accounts, holdings, markets, summary } = ...`

2024-10-19 12:52 UTC, dtslvr commented on apps/api/src/app/user/user.service.ts
> +        new AllocationClusterRiskEmergingMarkets(undefined, 0, 0).getSettings(
`undefined, undefined, undefined`

2024-10-19 12:52 UTC, dtslvr commented on apps/api/src/models/rules/allocation-cluster-risk/emerging-markets.ts
> +        )}% of your initial investment (${(emergingMarketsValueRatio * 100).toPrecision(3)}%)`,
of your **current** investment

2024-10-19 12:52 UTC, dtslvr commented on apps/api/src/models/rules/allocation-cluster-risk/emerging-markets.ts
> +        )}% of your initial investment (${(emergingMarketsValueRatio * 100).toPrecision(3)}%)`,
of your **current** investment

2024-10-20 21:06 UTC, vitalymatyushik commented
thank you @dtslvr!
I've addressed the comments and added a new section 

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/63948923-7da5-4cc5-a524-abe42689ee9a">

2024-10-22 18:14 UTC, dtslvr approved these changes
This is a great addition! 🙌🏻 Thank you, @vitalymatyushik!
Ready to merge.

2024-10-22 18:19 UTC, merged