Improve Font Color assignmnet in tree map chart component
ghostfolio/ghostfolio pull request #3954
Opened 2024-10-19 09:11 UTC by VeerChaurasia

Improve Font Color and background color

2024-10-20 07:07 UTC, dtslvr requested changes
Thank you for the contribution, @VeerChaurasia.
I have reviewed the changes and added a few comments.

2024-10-20 07:07 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +interface ColorConfig {
Please move to `libs/ui/src/lib/treemap-chart/interfaces/interfaces.ts`

2024-10-20 07:07 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> -  public ngAfterViewInit() {
Why has this been removed?

2024-10-20 07:07 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> -  public ngOnChanges() {
Why has this been removed?

2024-10-20 07:07 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> -  public ngOnDestroy() {
Why has this been removed?

2024-10-20 07:07 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +              const colorConfig = this.getColorConfig(
`const { fontColor } = this.getColorConfig(`

2024-10-20 07:07 UTC, dtslvr commented on libs/ui/src/lib/treemap-chart/treemap-chart.component.ts
> +            const colorConfig = this.getColorConfig(
`const { backgroundColor } = this.getColorConfig(`

2024-10-21 17:35 UTC, VeerChaurasia commented
Hey @dtslvr can you pls review it

2024-10-22 19:18 UTC, dtslvr approved these changes
Thanks for your contribution, @VeerChaurasia! 👍🏻
I have slightly adapted the code. Ready to merge now.

2024-10-23 12:32 UTC, merged