#3865 Add 'createdAt' field to PortfolioSnapshot and PublicPortfolioResponse
ghostfolio/ghostfolio pull request #3965
Opened 2024-10-20 08:15 UTC by verbindolai

### Issue
https://github.com/ghostfolio/ghostfolio/issues/3865

### What
Add `createdAt` field to PortfolioSnapshot and PublicPortfolioResponse to provide additional information for the client about the freshness of the calculations.

### How
- Added the field to multiple iterfaces
- Set the field whenever a snapshot is created and pass it through multiple methods to provide it in PublicPortfolioResponse

2024-10-24 17:36 UTC, dtslvr requested changes
Thanks a lot for your contribution, @verbindolai 😎 I have reviewed the changes and added a few comments.

I think it would make sense to get rid of `expiration` in [PortfolioSnapshotValue](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/interfaces/snapshot-value.interface.ts#L2) and reuse `createdAt` from `portfolioSnapshot` instead, because these concepts are redundant now. Could you adapt that as well?

2024-10-24 17:36 UTC, dtslvr commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator.ts
> +      createdAt: new Date(),
Please move just before `historicalData: [],`

2024-10-24 17:36 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +          createdAt: undefined,
`createdAt: new Date(),` ❓

2024-10-24 17:36 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +        createdAt: createdAt,
Please use the short form `createdAt,` and move up ⬆️

2024-10-24 17:36 UTC, dtslvr commented on apps/api/src/app/portfolio/portfolio.service.ts
> +      createdAt: createdAt,
Please use the short form `createdAt,` and move up ⬆️

2024-10-24 17:36 UTC, dtslvr commented on libs/common/src/lib/interfaces/responses/public-portfolio-response.interface.ts
> +  createdAt: Date;
Can you move it to `PublicPortfolioResponseV1` please?

2024-11-23 18:23 UTC, dtslvr commented
Hi @verbindolai

Any progress on the PR? Let me know if you need support regarding the code review.

2025-02-21 09:39 UTC, csehatt741 commented on libs/common/src/lib/interfaces/responses/public-portfolio-response.interface.ts
> +  createdAt: Date;
Moved into `PublicPortfolioResponseV1`

2025-02-21 09:42 UTC, csehatt741 commented on apps/api/src/app/portfolio/portfolio.service.ts
> +          createdAt: undefined,
`createdAt: new Date()`

2025-02-21 09:47 UTC, csehatt741 commented on apps/api/src/app/portfolio/calculator/twr/portfolio-calculator.ts
> +      createdAt: new Date(),
```
createdAt:` new Date(),
historicalData: [],
```

2025-02-21 09:49 UTC, csehatt741 commented on apps/api/src/app/portfolio/portfolio.service.ts
> +        createdAt: createdAt,
```
createdAt,
netPerformance,
```

2025-02-21 09:50 UTC, csehatt741 commented on apps/api/src/app/portfolio/portfolio.service.ts
> +      createdAt: createdAt,
```
createdAt,
annualizedPerformancePercent,
```

2025-03-17 21:31 UTC, dtslvr commented
Superseded by https://github.com/ghostfolio/ghostfolio/pull/4350.

2025-03-17 21:31 UTC, closed without merging