Implement range slider in rule settings dialog #3972
ghostfolio/ghostfolio pull request #4043
Opened 2024-11-14 02:55 UTC by amandee27

Implemented the feature #3972

## Test

![Recording (1)](https://github.com/user-attachments/assets/25ad35c7-1ab1-400e-aa7c-06a305015437)

Based on the review suggestions this is the updated UI.

<br/>

<img width="1436" alt="Screenshot 2024-11-15 at 17 11 11" src="https://github.com/user-attachments/assets/a2cf5e47-322c-413c-b529-4d3935520df4">

<br/>

<img width="1438" alt="Screenshot 2024-11-15 at 17 10 56" src="https://github.com/user-attachments/assets/76555767-ae53-4ebe-ad55-609abf1af20c">

2024-11-14 20:22 UTC, dtslvr requested changes
Thanks for your contribution, @amandee27! These changes in the template are a bit hard to review, however the tests were successful 🤓

I have added a few comments. Most of them are style-related to make the slider spanning over the full dialog width.

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      [ngClass]="{
I think you can remove this. Because of the `@if` statement, the condition of `d-none` will never be true.

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      [ngClass]="{ 'd-none': !data.rule.configuration.thresholdMin }"
This is fine, because you only want to display this slider if `thresholdMin` is set

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      [ngClass]="{ 'd-none': !data.rule.configuration.thresholdMax }"
This is fine, because you only want to display this slider if `thresholdMax` is set

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +        <ng-container i18n>Threshold</ng-container>:
_Threshold range_ might be clearer

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      @if (data.rule.configuration.threshold.unit === '%') {
Can you wrap the slider including labels with `<div class="align-items-center d-flex w-100">`

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
>        @if (data.rule.configuration.threshold.unit === '%') {
Can you wrap the slider including labels with `<div class="align-items-center d-flex w-100">`

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      @if (data.rule.configuration.threshold.unit === '%') {
Can you wrap the slider including labels with `<div class="align-items-center d-flex w-100">`

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
Please add
```
label {
  margin-bottom: 0;
}
```
to `rule-settings-dialog.scss`

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      <mat-slider
Please add `class="flex-grow-1"`

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      <mat-slider
Please add `class="flex-grow-1"`

2024-11-14 20:22 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
> +      <mat-slider
Please add `class="flex-grow-1"`

2024-11-15 17:18 UTC, amandee27 commented
@dtslvr I have made the requested changes. Please have a look.

2024-11-16 10:37 UTC, dtslvr approved these changes
Thank you for this contribution, @amandee27! 🙌🏻
Ready to merge now.

2024-11-16 10:37 UTC, dtslvr commented on apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html
To make sure the custom style is only in the scope of this dialog and does not leak, it needs to be wrapped in `:host {}` ℹ️

2024-11-16 11:17 UTC, merged