Bugfix/storybook build errors
ghostfolio/ghostfolio pull request #4168
Opened 2024-12-31 06:47 UTC by carlos-ds

Closes #4156

2025-01-02 09:49 UTC, dtslvr requested changes
Thanks for your contribution, @carlos-ds 👍🏻
This looks good! I have left a few comments to maintain consistency with the general style.

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/fire-calculator/fire-calculator.component.stories.ts
> +        MatDatepickerModule,
Can you move up to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/fire-calculator/fire-calculator.component.stories.ts
> +        GfFireCalculatorComponent
Can you move up to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/line-chart/line-chart.component.stories.ts
> +      imports: [GfLineChartComponent, CommonModule, NgxSkeletonLoaderModule]
Can you keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.stories.ts
> +        CommonModule,
Can you move up to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/trend-indicator/trend-indicator.component.stories.ts
> +    dateRange: '1d'
Can you move up to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/trend-indicator/trend-indicator.component.stories.ts
> +    dateRange: '1d'
Can you move up to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/value/value.component.stories.ts
> +    locale: 'en-US',
Can you move down to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/value/value.component.stories.ts
> +    locale: 'en-US',
Can you move down to keep the alphabetical order?

2025-01-02 09:49 UTC, dtslvr commented on libs/ui/src/lib/value/value.component.stories.ts
> +    locale: 'en-US',
Can you move down to keep the alphabetical order?

2025-01-02 22:05 UTC, carlos-ds commented
> Thanks for your contribution, @carlos-ds 👍🏻 This looks good! I have left a few comments to maintain consistency with the general style.

Ah my bad, I didn't notice array items and object keys were alphabetically ordered. This should be resolved now.

2025-01-06 21:38 UTC, dtslvr approved these changes
Great work, @carlos-ds! 🙌🏻

2025-01-06 21:49 UTC, merged